[build]
  publish = "frontend"
  command = "echo 'No build command needed for static site'"

[[redirects]]
  from = "/api/*"
  to = "https://aiia-saas-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
